export enum ZoneName {
    DECK = "DECK",
    HAND = "HAND",
    WAITING_ROOM = "WAITING ROOM",
    CLOCK = "CLOCK",
    LEVEL = "LEVEL",
    STOCK = "STOCK",
    CLIMAX = "CLIMAX",
    MEMORY = "MEMORY",
    RESOLUTION = "RESOLUTION",

    CENTER_STAGE_LEFT = "CENTER STAGE LEFT",
    CENTER_STAGE_MIDDLE = "CENTER STAGE MIDDLE",
    CENTER_STAGE_RIGHT = "CENTER STAGE RIGHT",
    BACK_STAGE_LEFT = "BACK STAGE LEFT",
    BACK_STAGE_RIGHT = "BACK STAGE RIGHT",

    CENTER_STAGE_LEFT_MARKER = "CENTER STAGE LEFT MARKER",
    CENTER_STAGE_MIDDLE_MARKER = "CENTER STAGE MIDDLE MARKER",
    CENTER_STAGE_RIGHT_MARKER = "CENTER STAGE RIGHT MARKER",
    BACK_STAGE_LEFT_MARKER = "BACK STAGE LEFT MARKER",
    BACK_STAGE_RIGHT_MARKER = "BACK STAGE RIGHT MARKER"

}