package ton.klay.wspro.core.game.formats.standard.triggers;

public enum TriggerName {
    CARD_MOVED,
    CARD_DRAWN,
    CARD_DISCARDED,
    ZONE_SHUFFLED,
    PLAYER_LOST,
    GAME_OVER,
    DECK_EMPTY,
    REFRESH_POINT_ADDED,
    TURN_STARTED,
    CARD_ORIENTED,
    PHASE_START,
    CLOCK_FULL,
    LEVELED_UP,
    CARD_CLOCKED,
    CARD_ENCORED,
    CARD_PLAYED,
    DAMAGE_PROCESSED,
    END_OF_ATTACK,
    TRIGGER_CARD_CHECKED,
    WILL_ATTACK,
    REVERSED_IN_BATTLE,
    COST_PAID,
    WILL_PAY_STOCK, ATTACK_SETUP
}
